[custom]
;fork from ACL4SSR_Online_Full_NoAuto.ini 规则
;适合中国大陆网络环境
;移除了广告拦截、网易音乐，补上大集合漏的部分，还添加了自定义条目
;方便在 gist 上更新规则，而不需要在软件端缓慢地 sed 修改文件

;去广告：支持
;自动测速：不支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：支持
;增强国外GFW：支持

;设置规则标志位
; 本地一份远程一份，允许本地预览
ruleset=🚄任意代理,Custom.list
ruleset=🚄任意代理,https://cdn.gh-proxy.org/raw.githubusercontent.com/enihsyou/subconverter/refs/heads/main/Custom.list
ruleset=🎯全球直连,CustomAllow.list
ruleset=🎯全球直连,https://cdn.gh-proxy.org/raw.githubusercontent.com/enihsyou/subconverter/refs/heads/main/CustomAllow.list
ruleset=🛳️美国特供,CustomUS.list
ruleset=🛳️美国特供,https://cdn.gh-proxy.org/raw.githubusercontent.com/enihsyou/subconverter/refs/heads/main/CustomUS.list
ruleset=🤖人工智能,CustomGemini.list
ruleset=🤖人工智能,https://cdn.gh-proxy.org/raw.githubusercontent.com/enihsyou/subconverter/refs/heads/main/CustomGemini.list

ruleset=⛴️网飞服务,https://cdn.gh-proxy.org/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=🤖人工智能,https://cdn.gh-proxy.org/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Gemini/Gemini.list
ruleset=🤖人工智能,https://cdn.gh-proxy.org/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bing.list
ruleset=🤖人工智能,https://cdn.gh-proxy.org/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.list
ruleset=🤖人工智能,https://cdn.gh-proxy.org/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Copilot/Copilot.list
ruleset=🤖人工智能,https://cdn.gh-proxy.org/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Claude.list
ruleset=🎯全球直连,https://cdn.gh-proxy.org/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.list
ruleset=🎯全球直连,https://cdn.gh-proxy.org/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯全球直连,https://cdn.gh-proxy.org/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=🎯全球直连,https://cdn.gh-proxy.org/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=🎯全球直连,https://cdn.gh-proxy.org/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=🎯全球直连,https://cdn.gh-proxy.org/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetEaseMusic.list
ruleset=🎯全球直连,https://cdn.gh-proxy.org/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMedia/ChinaMedia.list
ruleset=🎯全球直连,https://cdn.gh-proxy.org/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯全球直连,https://cdn.gh-proxy.org/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯全球直连,https://cdn.gh-proxy.org/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/GameDownloadCN/GameDownloadCN.list
ruleset=🎯全球直连,https://cdn.gh-proxy.org/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/SteamCN/SteamCN.list
ruleset=🎯全球直连,https://cdn.gh-proxy.org/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Cloud/CloudCN/CloudCN.list
ruleset=🎯全球直连,https://cdn.gh-proxy.org/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AmazonCN/AmazonCN.list
ruleset=🎯全球直连,https://cdn.gh-proxy.org/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GovCN/GovCN.list
ruleset=🎯全球直连,https://cdn.gh-proxy.org/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/MicrosoftEdge/MicrosoftEdge.list
ruleset=🎯全球直连,https://cdn.gh-proxy.org/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/NTPService/NTPService.list
ruleset=🎯全球直连,https://cdn.gh-proxy.org/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.list
ruleset=🎯全球直连,[]GEOIP,CN
ruleset=🚄任意代理,https://cdn.gh-proxy.org/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=🚄任意代理,https://cdn.gh-proxy.org/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=🚄任意代理,https://cdn.gh-proxy.org/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Docker.list
ruleset=🚄任意代理,https://cdn.gh-proxy.org/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Github.list
; 这些网站不一定需要代理，先禁用看看是否影响使用
; ruleset=🚄任意代理,https://cdn.gh-proxy.org/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Developer.list
ruleset=🚄任意代理,https://cdn.gh-proxy.org/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitBook/GitBook.list
ruleset=🚄任意代理,https://cdn.gh-proxy.org/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=🚄任意代理,https://cdn.gh-proxy.org/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list
ruleset=🚄任意代理,https://cdn.gh-proxy.org/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Xbox.list
ruleset=🚄任意代理,https://cdn.gh-proxy.org/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
ruleset=🚄任意代理,https://cdn.gh-proxy.org/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=🚄任意代理,https://cdn.gh-proxy.org/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list
ruleset=🚄任意代理,https://cdn.gh-proxy.org/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=🚄任意代理,https://cdn.gh-proxy.org/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list
ruleset=🚄任意代理,https://cdn.gh-proxy.org/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🚄任意代理,https://cdn.gh-proxy.org/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Proxy/Proxy.list
ruleset=🐟漏网之鱼,[]FINAL

;设置分组标志位
;custom_proxy_group=Group_Name`url-test|fallback|load-balance`Rule_1`Rule_2`...`test_url`interval[,timeout][,tolerance]
;custom_proxy_group=Group_Name`select`Rule_1`Rule_2`...
custom_proxy_group=🚄任意代理`select`.*
custom_proxy_group=🤖人工智能`select`.*
custom_proxy_group=🛳️美国特供`select`.*
custom_proxy_group=⛴️网飞服务`select`.*
custom_proxy_group=🎯全球直连`select`[]DIRECT`[]🚄任意代理
custom_proxy_group=🐟漏网之鱼`select`[]DIRECT`[]🚄任意代理

enable_rule_generator=true
overwrite_original_rules=false
