"""
ssp 在 2025-12-27 启用了订阅激活策略，且并未提供 OpenAPI, 因此无法继续使用 GitHub Action 来自动化生成 Gist。这个文件用来在本地完成上传动作。
"""

import configparser
import os
import sys
from pathlib import Path

from github import Auth, Github
from github.InputFileContent import InputFileContent

script_name = os.path.basename(__file__)


def main():
    if len(sys.argv) < 2:
        print(f"Usage: python {script_name} <upload_file> [<upload_name>]")
        sys.exit(1)

    upload_file = sys.argv[1]
    upload_name = sys.argv[2] if len(sys.argv) > 2 else upload_file

    config = configparser.ConfigParser()
    config.read("gistconf.ini")

    token = config["common"]["token"]
    gist_id = config["common"]["id"]

    upload_content = Path(upload_file).read_text(encoding="utf-8")

    g = Github(auth=Auth.Token(token))

    try:
        gist = g.get_gist(gist_id)
        gist.edit(
            description=f"clash profile generated by {script_name}",
            files={
                upload_name: InputFileContent(upload_content),
            },
        )
        print(f"Gist created successfully: {gist.html_url}")
    except Exception as e:
        print(f"Error creating gist: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
